name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: healthcheck
        run: mvn test -Dtest=HealthCheckTest
    - name: contrato
        run: mvn test -Dtest=ContratoTest
    - name: funcional
        run: mvn test -Dtest=FuncionalTest